export const BLOGS = [
  {
    id: 1,
    title: "Steins;Gate – When Time Refuses to Obey",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY3OXyAtH8S-DFCWUwa0-4uyzthMjC3su8kA&s",
    description: "A deep dive into causality, timelines, and the emotional cost of rewriting fate.",
    content: "Steins;Gate explores the fragile boundary between curiosity and consequence, rated 9.07 on MyAnimeList with over 1.5 million members.[web:1][web:4]",
    anime: {
      episodes: 24,
      members: 1500000,
      rating: 9.07,
      genres: ["Sci-Fi", "Thriller"],
      type: "TV",
    },
    readTime: "6 min read",
    tag: "Sci-Fi",
  },
  {
    id: 2,
    title: "Attack on Titan – Freedom at a Terrible Price",
    image: "https://i.ytimg.com/vi/1RGvDJV6gIA/sddefault.jpg",
    description: "What does freedom mean in a world surrounded by walls and war?",
    content: "Attack on Titan delves into cycles of hatred and survival, boasting around 2.5 million members and a 8.54 rating on MAL.[web:1][web:6]",
    anime: {
      episodes: 89,
      members: 2500000,
      rating: 8.54,
      genres: ["Action", "Drama", "Fantasy"],
      type: "TV",
    },
    readTime: "7 min read",
    tag: "Action",
  },
  {
    id: 3,
    title: "Your Name – A Thread Across Time",
    image: "https://wallpapers.com/images/hd/your-name-taki-and-mitsuha-red-string-knd59f7ecab132ma.jpg",
    description: "A poetic story of love, loss, and cosmic coincidence.",
    content: "Makoto Shinkai's masterpiece intertwines distance and destiny, holding a 9.37 MAL score with 2 million members.[web:4]",
    anime: {
      episodes: 1,
      members: 2000000,
      rating: 9.37,
      genres: ["Drama", "Romance", "Supernatural"],
      type: "Movie",
    },
    readTime: "5 min read",
    tag: "Romance",
  },
  {
    id: 4,
    title: "Fullmetal Alchemist: Brotherhood – The Ultimate Sacrifice",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmWlojQ8V1jRWGVlLFxNjk9VamUmbiBdSIjg&s",
    description: "Alchemy, atonement, and the bonds that define humanity.",
    content: "Fullmetal Alchemist: Brotherhood tops charts at 9.09 on MAL, with millions of fans praising its epic storyline.[web:1][web:4]",
    anime: {
      episodes: 64,
      members: 3000000,
      rating: 9.09,
      genres: ["Action", "Adventure", "Drama"],
      type: "TV",
    },
    readTime: "8 min read",
    tag: "Adventure",
  },
  {
    id: 5,
    title: "Hunter x Hunter (2011) – The Hunter's Oath",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgZihkfu1YaZILHSHG1NLcQCuE7hAUpQ2wzw&s",
    description: "Friendship, rivalry, and the endless pursuit of strength.",
    content: "Madhouse's adaptation earns 9.03 on MAL, captivating over 2 million members with its depth.[web:1][web:4]",
    anime: {
      episodes: 148,
      members: 2200000,
      rating: 9.03,
      genres: ["Action", "Adventure", "Shounen"],
      type: "TV",
    },
    readTime: "9 min read",
    tag: "Shounen",
  },
  {
    id: 6,
    title: "Frieren: Beyond Journey's End – Echoes of Eternity",
    image: "https://m.media-amazon.com/images/S/pv-target-images/0cee73934e4d8cc9fe65c4ab759b4c1b049f75fff3f4c52b273c2699efadd7d1._SX1080_FMjpg_.jpg",
    description: "An elf mage reflects on time, loss, and unspoken regrets.",
    content: "Frieren leads 2020s ratings at 9.35 on MAL with 1.2 million members, redefining fantasy.[web:4][web:12]",
    anime: {
      episodes: 28,
      members: 1241934,
      rating: 9.35,
      genres: ["Adventure", "Drama", "Fantasy"],
      type: "TV",
    },
    readTime: "7 min read",
    tag: "Fantasy",
  },
  {
    id: 7,
    title: "Gintama – Laughter in a Samurai World",
    image: "https://wallpapers.com/images/hd/gintama-background-40wtrmt63sqeqv8o.jpg",
    description: "Parody, action, and heart in Edo's alien-infested streets.",
    content: "Gintama blends comedy and drama for a 8.93 MAL score across its long run.[web:1][web:4]",
    anime: {
      episodes: 367,
      members: 1200000,
      rating: 8.93,
      genres: ["Action", "Comedy", "Sci-Fi"],
      type: "TV",
    },
    readTime: "10 min read",
    tag: "Comedy",
  },
  {
    id: 8,
    title: "Death Note – Justice or Vengeance?",
    image: "https://wallpapers.com/images/featured/death-note-htruruirspqq0zot.jpg",
    description: "A notebook that kills sparks a battle of intellects.",
    content: "Death Note's cat-and-mouse game holds 8.62 on MAL with massive popularity.[web:3][web:6]",
    anime: {
      episodes: 37,
      members: 4500000,
      rating: 8.62,
      genres: ["Mystery", "Supernatural", "Thriller"],
      type: "TV",
    },
    readTime: "6 min read",
    tag: "Thriller",
  },
  {
    id: 9,
    title: "One Piece – Dreams on the Grand Line",
    image: "https://wallpapers.com/images/hd/one-piece-pictures-vg1pferor2m9vo5l.jpg",
    description: "Pirates chase the ultimate treasure in a vast ocean world.",
    content: "One Piece endures with 8.72 MAL rating and millions of members.[web:4]",
    anime: {
      episodes: 1100,
      members: 5000000,
      rating: 8.72,
      genres: ["Action", "Adventure", "Fantasy"],
      type: "TV",
    },
    readTime: "11 min read",
    tag: "Pirate",
  },
  {
    id: 10,
    title: "Cowboy Bebop – Bounty Hunters in Space",
    image: "https://images4.alphacoders.com/661/thumb-1920-661990.png",
    description: "Jazz, guns, and past regrets across the solar system.",
    content: "Cowboy Bebop's style earns 8.75 on MAL.[web:4]",
    anime: {
      episodes: 26,
      members: 1800000,
      rating: 8.75,
      genres: ["Action", "Sci-Fi"],
      type: "TV",
    },
    readTime: "5 min read",
    tag: "Space",
  },
  {
    id: 11,
    title: "Code Geass – Rebellion of the Black Knights",
    image: "https://w0.peakpx.com/wallpaper/462/346/HD-wallpaper-code-geass-black-knights-code-geass-kallen-c2-cc-zero-geass-lelouch.jpg",
    description: "Power, strategy, and the cost of revolution.",
    content: "Code Geass scores 8.70 on MAL for its mecha intrigue.[web:4]",
    anime: {
      episodes: 50,
      members: 2000000,
      rating: 8.70,
      genres: ["Action", "Mecha", "Military"],
      type: "TV",
    },
    readTime: "7 min read",
    tag: "Mecha",
  },
  {
    id: 12,
    title: "Vinland Saga – Viking Sagas of Vengeance",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbnDKN5N0QDBoQ-GbrCE0VXqLi_Cde9szZ9g&s",
    description: "From warrior to seeker of paradise.",
    content: "Vinland Saga impresses at 8.75 MAL rating.[web:4]",
    anime: {
      episodes: 48,
      members: 1500000,
      rating: 8.75,
      genres: ["Action", "Drama", "Historical"],
      type: "TV",
    },
    readTime: "8 min read",
    tag: "Historical",
  },
  {
    id: 13,
    title: "Bleach: Thousand-Year Blood War – Final Arc Glory",
    image: "https://wallpapers.com/images/hd/ichigo-and-zangetsu-bleach-4k-ultra-hd-fanart-ymhbljxwfhxsnm3n.jpg",
    description: "Soul Reapers vs Quincy in epic conclusion.",
    content: "Bleach TYBW hits 9.01 on MAL.[web:1]",
    anime: {
      episodes: 39,
      members: 1000000,
      rating: 9.01,
      genres: ["Action", "Supernatural"],
      type: "TV",
    },
    readTime: "6 min read",
    tag: "Shounen",
  },
  {
    id: 14,
    title: "Monster – The Hunt for Johan Liebert",
    image: "https://images.alphacoders.com/526/526487.jpg",
    description: "A surgeon's moral dilemma unleashes terror.",
    content: "Monster's psychological depth earns 8.88 MAL.[web:4]",
    anime: {
      episodes: 74,
      members: 900000,
      rating: 8.88,
      genres: ["Drama", "Mystery", "Thriller"],
      type: "TV",
    },
    readTime: "9 min read",
    tag: "Psychological",
  },
  {
    id: 15,
    title: "Violet Evergarden – Letters of the Heart",
    image: "https://images.alphacoders.com/888/888889.jpg",
    description: "An auto-memory doll learns human emotion.",
    content: "Violet Evergarden rates 8.68 on MAL.[web:4]",
    anime: {
      episodes: 13,
      members: 1600000,
      rating: 8.68,
      genres: ["Drama", "Slice of Life"],
      type: "TV",
    },
    readTime: "5 min read",
    tag: "Drama",
  },
  {
    id: 16,
    title: "Jujutsu Kaisen – Curses and Sorcerers",
    image: "https://images.alphacoders.com/1126/1126652.jpg",
    description: "Modern sorcery battles ancient curses.",
    content: "Jujutsu Kaisen thrives with high popularity.[web:6]",
    anime: {
      episodes: 47,
      members: 3000000,
      rating: 8.49,
      genres: ["Action", "Supernatural"],
      type: "TV",
    },
    readTime: "7 min read",
    tag: "Supernatural",
  },
  {
    id: 17,
    title: "Demon Slayer – Breathing Styles Unleashed",
    image: "https://images.alphacoders.com/1024/1024924.jpg",
    description: "Slayers protect humanity from demons.",
    content: "Demon Slayer scores 8.49 on MAL.[web:6]",
    anime: {
      episodes: 60,
      members: 4000000,
      rating: 8.49,
      genres: ["Action", "Fantasy"],
      type: "TV",
    },
    readTime: "6 min read",
    tag: "Action",
  },
  {
    id: 18,
    title: "My Hero Academia – Plus Ultra Heroes",
    image: "https://images.alphacoders.com/936/936254.jpg",
    description: "Quirk society trains future heroes.",
    content: "My Hero Academia holds 7.88 average.[web:6]",
    anime: {
      episodes: 150,
      members: 3500000,
      rating: 7.88,
      genres: ["Action", "Super Power"],
      type: "TV",
    },
    readTime: "8 min read",
    tag: "Hero",
  },
  {
    id: 19,
    title: "Naruto – Ninja Way Perseverance",
    image: "https://images.alphacoders.com/497/497892.jpg",
    description: "From outcast to Hokage legend.",
    content: "Naruto's saga rates 7.99 on MAL.[web:6]",
    anime: {
      episodes: 720,
      members: 5000000,
      rating: 7.99,
      genres: ["Action", "Adventure"],
      type: "TV",
    },
    readTime: "10 min read",
    tag: "Ninja",
  },
  {
    id: 20,
    title: "Legend of the Galactic Heroes – Space Opera Epic",
    image: "https://images.alphacoders.com/102/102483.jpg",
    description: "Galactic empires clash in strategy and philosophy.",
    content: "Legend of Galactic Heroes masters at 9.02 MAL.[web:4]",
    anime: {
      episodes: 110,
      members: 500000,
      rating: 9.02,
      genres: ["Sci-Fi", "Space"],
      type: "OVA",
    },
    readTime: "12 min read",
    tag: "Space Opera",
  },
];

export default BLOGS;
